import { WorkspaceCollectionPage, type CollectionConfig } from '@/features/workspace/WorkspaceCollectionPage';

const configs: Record<string, CollectionConfig> = {
  requests: { module: 'requests', apiKey: 'requests', label: 'Đơn & đề xuất', eyebrow: 'Quy trình nội bộ', description: 'Tạo, theo dõi và tra cứu các đơn từ một nơi.', searchPlaceholder: 'Tìm theo tên đơn, nội dung…', primary: { label: 'Tạo đơn', action: 'create-request', kind: 'request' }, filters: ['Chờ duyệt', 'Đã duyệt', 'Từ chối'], stats: [{ label: 'Đã gửi', value: '8' }, { label: 'Chờ duyệt', value: '4' }, { label: 'Đã duyệt', value: '26' }, { label: 'Từ chối', value: '1' }] },
  cloud: { module: 'cloud', apiKey: 'cloud', label: 'Cloud nội bộ', eyebrow: 'Lưu trữ & chia sẻ', description: 'Quản lý tệp, thư mục và quyền truy cập nội bộ.', searchPlaceholder: 'Tìm tài liệu, thư mục…', primary: { label: 'Tải tệp', action: 'upload', kind: 'upload' }, secondary: { label: 'Tạo thư mục', action: 'create-folder', kind: 'upload' }, filters: ['Thư mục', 'PDF', 'Bảng tính'], stats: [{ label: 'Dung lượng sử dụng', value: '32 GB' }, { label: 'Tổng dung lượng', value: '50 GB' }, { label: 'Tệp được chia sẻ', value: '28' }, { label: 'Cập nhật gần đây', value: '12' }], view: 'tiles' },
  meetings: { module: 'meetings', apiKey: 'meetings', label: 'Họp trực tuyến', eyebrow: 'Cộng tác trực tuyến', description: 'Tạo, tham gia và quản lý lịch họp nội bộ.', searchPlaceholder: 'Tìm cuộc họp…', primary: { label: 'Tạo cuộc họp', action: 'create-meeting', kind: 'meeting' }, secondary: { label: 'Tham gia bằng ID', action: 'join-meeting', kind: 'meeting' }, filters: ['Sắp diễn ra', 'Đã kết thúc'], stats: [{ label: 'Hôm nay', value: '2' }, { label: 'Tuần này', value: '6' }, { label: 'Bản ghi', value: '14' }, { label: 'Tổng thời lượng', value: '9,5 giờ' }] },
  evaluations: { module: 'evaluations', apiKey: 'evaluations', label: 'Đánh giá lao động', eyebrow: 'Hiệu suất & phát triển', description: 'Tự đánh giá, chấm điểm và theo dõi kết quả theo kỳ.', searchPlaceholder: 'Tìm phiếu hoặc nhân sự…', filters: ['Đang thực hiện', 'Chờ chấm', 'Đang chấm'], stats: [{ label: 'Tiến độ', value: '8/10' }, { label: 'Điểm hiện tại', value: '86,5' }, { label: 'Chờ chấm', value: '2' }, { label: 'Hạn hoàn thành', value: '15/08' }] },
  library: { module: 'library', apiKey: 'library', label: 'Thư viện số', eyebrow: 'Kho tri thức nội bộ', description: 'Tra cứu tài liệu, ấn phẩm và nội dung số của cơ quan.', searchPlaceholder: 'Tìm tiêu đề, tác giả, nội dung…', primary: { label: 'Tải tài liệu', action: 'upload-library', kind: 'library' }, filters: ['PDF', 'Hình ảnh', 'Tài liệu'], stats: [{ label: 'Tài liệu', value: '1.486' }, { label: 'Hình ảnh', value: '8.240' }, { label: 'Mới cập nhật', value: '32' }, { label: 'Đã lưu', value: '18' }], view: 'tiles' },
  experts: { module: 'experts', apiKey: 'experts', label: 'Chuyên gia', eyebrow: 'Mạng lưới chuyên môn', description: 'Tra cứu chuyên gia và lịch sử cộng tác với cơ quan.', searchPlaceholder: 'Tìm tên, lĩnh vực, đơn vị…', filters: ['Kinh tế', 'Công nghệ', 'Giáo dục'], stats: [{ label: 'Chuyên gia', value: '126' }, { label: 'Lĩnh vực', value: '18' }, { label: 'Đang cộng tác', value: '42' }, { label: 'Đánh giá trung bình', value: '4,8' }], view: 'experts' },
};

export const RequestsPage = () => <WorkspaceCollectionPage config={configs.requests} />;
export const CloudPage = () => <WorkspaceCollectionPage config={configs.cloud} />;
export const MeetingsPage = () => <WorkspaceCollectionPage config={configs.meetings} />;
export const EvaluationsPage = () => <WorkspaceCollectionPage config={configs.evaluations} />;
export const LibraryPage = () => <WorkspaceCollectionPage config={configs.library} />;
export const ExpertsPage = () => <WorkspaceCollectionPage config={configs.experts} />;
